{
 "title": "AWS Backup Overview",
 "tags": [
  "aws",
  "cloudwatch",
  "backup"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "cloudwatch" },
   {
    "name": "region",
    "label": "Region",
    "query": "us-east-1,us-east-2,us-west-1,us-west-2,eu-west-1,eu-west-2,eu-west-3,eu-central-1,eu-north-1,ap-northeast-1,ap-northeast-2,ap-southeast-1,ap-southeast-2,ap-south-1,sa-east-1,ca-central-1"
   },
   {
    "name": "vault",
    "label": "Backup Vault",
    "query": {}
   },
   {
    "name": "resourcetype",
    "label": "Resource Type",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Backup Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backup Jobs Completed",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "BackupVaultName": "$vault" },
     "metricName": "NumberOfBackupJobsCompleted",
     "namespace": "AWS/Backup",
     "period": "300",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Backup Jobs Failed",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "BackupVaultName": "$vault" },
     "metricName": "NumberOfBackupJobsFailed",
     "namespace": "AWS/Backup",
     "period": "300",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Recovery Points Completed",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "BackupVaultName": "$vault" },
     "metricName": "NumberOfRecoveryPointsCompleted",
     "namespace": "AWS/Backup",
     "period": "300",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Restore Jobs Failed",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "BackupVaultName": "$vault" },
     "metricName": "NumberOfRestoreJobsFailed",
     "namespace": "AWS/Backup",
     "period": "300",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Copy Jobs Completed",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "BackupVaultName": "$vault" },
     "metricName": "NumberOfCopyJobsCompleted",
     "namespace": "AWS/Backup",
     "period": "300",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Copy Jobs Failed",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "BackupVaultName": "$vault" },
     "metricName": "NumberOfCopyJobsFailed",
     "namespace": "AWS/Backup",
     "period": "300",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Restore Jobs Completed",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "BackupVaultName": "$vault" },
     "metricName": "NumberOfRestoreJobsCompleted",
     "namespace": "AWS/Backup",
     "period": "300",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Backup Jobs Expired",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "BackupVaultName": "$vault" },
     "metricName": "NumberOfBackupJobsExpired",
     "namespace": "AWS/Backup",
     "period": "300",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "Backup Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Backup Jobs Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "BackupVaultName": "$vault" },
     "metricName": "NumberOfBackupJobsCompleted",
     "namespace": "AWS/Backup",
     "period": "300",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "BackupVaultName": "$vault" },
     "metricName": "NumberOfBackupJobsFailed",
     "namespace": "AWS/Backup",
     "period": "300",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "BackupVaultName": "$vault" },
     "metricName": "NumberOfBackupJobsExpired",
     "namespace": "AWS/Backup",
     "period": "300",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Copy Jobs Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "BackupVaultName": "$vault" },
     "metricName": "NumberOfCopyJobsCompleted",
     "namespace": "AWS/Backup",
     "period": "300",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "BackupVaultName": "$vault" },
     "metricName": "NumberOfCopyJobsFailed",
     "namespace": "AWS/Backup",
     "period": "300",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "Recovery Points", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Recovery Points Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "BackupVaultName": "$vault" },
     "metricName": "NumberOfRecoveryPointsCompleted",
     "namespace": "AWS/Backup",
     "period": "300",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "BackupVaultName": "$vault" },
     "metricName": "NumberOfRecoveryPointsPartial",
     "namespace": "AWS/Backup",
     "period": "300",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "BackupVaultName": "$vault" },
     "metricName": "NumberOfRecoveryPointsExpired",
     "namespace": "AWS/Backup",
     "period": "300",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Restore Jobs Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "BackupVaultName": "$vault" },
     "metricName": "NumberOfRestoreJobsCompleted",
     "namespace": "AWS/Backup",
     "period": "300",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "BackupVaultName": "$vault" },
     "metricName": "NumberOfRestoreJobsFailed",
     "namespace": "AWS/Backup",
     "period": "300",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "Recovery Point Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Recovery Points by Storage Tier",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "BackupVaultName": "$vault" },
     "metricName": "NumberOfRecoveryPointsCold",
     "namespace": "AWS/Backup",
     "period": "300",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "dimensions": { "BackupVaultName": "$vault" },
     "metricName": "NumberOfRecoveryPointsWarm",
     "namespace": "AWS/Backup",
     "period": "300",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "dimensions": { "BackupVaultName": "$vault" },
     "metricName": "NumberOfRecoveryPointsDeleting",
     "namespace": "AWS/Backup",
     "period": "300",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Backup Jobs by Resource Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "BackupVaultName": "$vault", "ResourceType": "$resourcetype" },
     "metricName": "NumberOfBackupJobsCompleted",
     "namespace": "AWS/Backup",
     "period": "300",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  }
 ]
}