{
 "title": "AWS EventBridge Overview",
 "tags": [
  "aws",
  "cloudwatch",
  "eventbridge",
  "events"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "cloudwatch" },
   {
    "name": "region",
    "label": "Region",
    "query": "us-east-1,us-east-2,us-west-1,us-west-2,eu-west-1,eu-west-2,eu-west-3,eu-central-1,eu-north-1,ap-northeast-1,ap-northeast-2,ap-southeast-1,ap-southeast-2,ap-south-1,sa-east-1,ca-central-1"
   },
   {
    "name": "rule",
    "label": "Rule",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "EventBridge Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Invocations",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "RuleName": "$rule" },
     "metricName": "Invocations",
     "namespace": "AWS/Events",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Failed Invocations",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "RuleName": "$rule" },
     "metricName": "FailedInvocations",
     "namespace": "AWS/Events",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Triggered Rules",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "RuleName": "$rule" },
     "metricName": "TriggeredRules",
     "namespace": "AWS/Events",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Dead Letter Invocations",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "RuleName": "$rule" },
     "metricName": "DeadLetterInvocations",
     "namespace": "AWS/Events",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Matched Events",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "RuleName": "$rule" },
     "metricName": "MatchedEvents",
     "namespace": "AWS/Events",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Throttled Rules",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "RuleName": "$rule" },
     "metricName": "ThrottledRules",
     "namespace": "AWS/Events",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Failed to Send to DLQ",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "RuleName": "$rule" },
     "metricName": "InvocationsFailedToBeSentToDlq",
     "namespace": "AWS/Events",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "Invocation Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Invocations Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "RuleName": "$rule" },
     "metricName": "Invocations",
     "namespace": "AWS/Events",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Failed Invocations Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "RuleName": "$rule" },
     "metricName": "FailedInvocations",
     "namespace": "AWS/Events",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "Event Matching", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Matched Events & Triggered Rules",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "RuleName": "$rule" },
     "metricName": "MatchedEvents",
     "namespace": "AWS/Events",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "RuleName": "$rule" },
     "metricName": "TriggeredRules",
     "namespace": "AWS/Events",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Throttled Rules Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "RuleName": "$rule" },
     "metricName": "ThrottledRules",
     "namespace": "AWS/Events",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "Dead Letter Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Dead Letter Queue Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "RuleName": "$rule" },
     "metricName": "DeadLetterInvocations",
     "namespace": "AWS/Events",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "RuleName": "$rule" },
     "metricName": "InvocationsFailedToBeSentToDlq",
     "namespace": "AWS/Events",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  }
 ]
}