{
 "title": "AWS FSx Overview",
 "tags": [
  "aws",
  "cloudwatch",
  "fsx",
  "storage"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "cloudwatch" },
   {
    "name": "region",
    "label": "Region",
    "query": "us-east-1,us-east-2,us-west-1,us-west-2,eu-west-1,eu-west-2,eu-west-3,eu-central-1,eu-north-1,ap-northeast-1,ap-northeast-2,ap-southeast-1,ap-southeast-2,ap-south-1,sa-east-1,ca-central-1"
   },
   {
    "name": "filesystem",
    "label": "File System",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "FSx Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Free Storage Capacity",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "FileSystemId": "$filesystem" },
     "metricName": "FreeStorageCapacity",
     "namespace": "AWS/FSx",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Minimum"
    }
   ]
  },
  {
   "title": "Disk Throughput Utilization",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "FileSystemId": "$filesystem" },
     "metricName": "DiskThroughputUtilization",
     "namespace": "AWS/FSx",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Disk IOPS Utilization",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "FileSystemId": "$filesystem" },
     "metricName": "DiskIopsUtilization",
     "namespace": "AWS/FSx",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Network Throughput Utilization",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "FileSystemId": "$filesystem" },
     "metricName": "NetworkThroughputUtilization",
     "namespace": "AWS/FSx",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Free Storage Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dimensions": { "FileSystemId": "$filesystem" },
     "metricName": "FreeStorageCapacity",
     "namespace": "AWS/FSx",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Minimum"
    }
   ]
  },
  { "title": "Throughput & IOPS Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Disk Throughput Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "FileSystemId": "$filesystem" },
     "metricName": "DiskThroughputUtilization",
     "namespace": "AWS/FSx",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Disk IOPS Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "FileSystemId": "$filesystem" },
     "metricName": "DiskIopsUtilization",
     "namespace": "AWS/FSx",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Network Throughput Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "FileSystemId": "$filesystem" },
     "metricName": "NetworkThroughputUtilization",
     "namespace": "AWS/FSx",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  { "title": "I/O Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Data Read/Write Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dimensions": { "FileSystemId": "$filesystem" },
     "metricName": "DataReadBytes",
     "namespace": "AWS/FSx",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "FileSystemId": "$filesystem" },
     "metricName": "DataWriteBytes",
     "namespace": "AWS/FSx",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Data Read/Write Operations (IOPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "FileSystemId": "$filesystem" },
     "metricName": "DataReadOperations",
     "namespace": "AWS/FSx",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "FileSystemId": "$filesystem" },
     "metricName": "DataWriteOperations",
     "namespace": "AWS/FSx",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Burst Credits (Windows File Server)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 }
  },
  {
   "title": "File Server Disk Throughput Balance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "FileSystemId": "$filesystem" },
     "metricName": "FileServerDiskThroughputBalance",
     "namespace": "AWS/FSx",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "File Server Disk IOPS Balance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "FileSystemId": "$filesystem" },
     "metricName": "FileServerDiskIopsBalance",
     "namespace": "AWS/FSx",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  }
 ]
}