{
 "title": "AWS NAT Gateway Overview",
 "tags": [
  "aws",
  "cloudwatch",
  "nat-gateway",
  "vpc",
  "networking"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "cloudwatch" },
   {
    "name": "region",
    "label": "Region",
    "query": "us-east-1,us-east-2,us-west-1,us-west-2,eu-west-1,eu-west-2,eu-west-3,eu-central-1,eu-north-1,ap-northeast-1,ap-northeast-2,ap-southeast-1,ap-southeast-2,ap-south-1,sa-east-1,ca-central-1"
   },
   {
    "name": "natgateway",
    "label": "NAT Gateway",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "NAT Gateway Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Connections",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "NatGatewayId": "$natgateway" },
     "metricName": "ActiveConnectionCount",
     "namespace": "AWS/NATGateway",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Port Allocation Errors",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "NatGatewayId": "$natgateway" },
     "metricName": "ErrorPortAllocation",
     "namespace": "AWS/NATGateway",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Packets Dropped",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "NatGatewayId": "$natgateway" },
     "metricName": "PacketsDropCount",
     "namespace": "AWS/NATGateway",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Idle Timeout Count",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "NatGatewayId": "$natgateway" },
     "metricName": "IdleTimeoutCount",
     "namespace": "AWS/NATGateway",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Bytes Out (to Internet)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "NatGatewayId": "$natgateway" },
     "metricName": "BytesOutToDestination",
     "namespace": "AWS/NATGateway",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Bytes In (from Internet)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "NatGatewayId": "$natgateway" },
     "metricName": "BytesInFromDestination",
     "namespace": "AWS/NATGateway",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Connection Attempts",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "NatGatewayId": "$natgateway" },
     "metricName": "ConnectionAttemptCount",
     "namespace": "AWS/NATGateway",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Connections Established",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "NatGatewayId": "$natgateway" },
     "metricName": "ConnectionEstablishedCount",
     "namespace": "AWS/NATGateway",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "NatGatewayId": "$natgateway" },
     "metricName": "ActiveConnectionCount",
     "namespace": "AWS/NATGateway",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Connection Attempts vs Established",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "NatGatewayId": "$natgateway" },
     "metricName": "ConnectionAttemptCount",
     "namespace": "AWS/NATGateway",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "NatGatewayId": "$natgateway" },
     "metricName": "ConnectionEstablishedCount",
     "namespace": "AWS/NATGateway",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "Traffic (Bytes)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Internet Traffic (Outbound/Inbound)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "dimensions": { "NatGatewayId": "$natgateway" },
     "metricName": "BytesOutToDestination",
     "namespace": "AWS/NATGateway",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "NatGatewayId": "$natgateway" },
     "metricName": "BytesInFromDestination",
     "namespace": "AWS/NATGateway",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "VPC Traffic (From/To Instances)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "dimensions": { "NatGatewayId": "$natgateway" },
     "metricName": "BytesInFromSource",
     "namespace": "AWS/NATGateway",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "NatGatewayId": "$natgateway" },
     "metricName": "BytesOutToSource",
     "namespace": "AWS/NATGateway",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "Packets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Internet Packets (Outbound/Inbound)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "dimensions": { "NatGatewayId": "$natgateway" },
     "metricName": "PacketsOutToDestination",
     "namespace": "AWS/NATGateway",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "NatGatewayId": "$natgateway" },
     "metricName": "PacketsInFromDestination",
     "namespace": "AWS/NATGateway",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "VPC Packets (From/To Instances)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "dimensions": { "NatGatewayId": "$natgateway" },
     "metricName": "PacketsInFromSource",
     "namespace": "AWS/NATGateway",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "NatGatewayId": "$natgateway" },
     "metricName": "PacketsOutToSource",
     "namespace": "AWS/NATGateway",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "Errors & Timeouts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Errors (Port Allocation & Dropped Packets)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "NatGatewayId": "$natgateway" },
     "metricName": "ErrorPortAllocation",
     "namespace": "AWS/NATGateway",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "NatGatewayId": "$natgateway" },
     "metricName": "PacketsDropCount",
     "namespace": "AWS/NATGateway",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Idle Timeout Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "NatGatewayId": "$natgateway" },
     "metricName": "IdleTimeoutCount",
     "namespace": "AWS/NATGateway",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  }
 ]
}