{
 "title": "AWS Redshift Overview",
 "tags": [
  "aws",
  "cloudwatch",
  "redshift",
  "data-warehouse"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "cloudwatch" },
   {
    "name": "region",
    "label": "Region",
    "query": "us-east-1,us-east-2,us-west-1,us-west-2,eu-west-1,eu-west-2,eu-west-3,eu-central-1,eu-north-1,ap-northeast-1,ap-northeast-2,ap-southeast-1,ap-southeast-2,ap-south-1,sa-east-1,ca-central-1"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Redshift Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ClusterIdentifier": "$cluster" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/Redshift",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Disk Space Used %",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ClusterIdentifier": "$cluster" },
     "metricName": "PercentageDiskSpaceUsed",
     "namespace": "AWS/Redshift",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Database Connections",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ClusterIdentifier": "$cluster" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/Redshift",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Health Status",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ClusterIdentifier": "$cluster" },
     "metricName": "HealthStatus",
     "namespace": "AWS/Redshift",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "WLM Queue Length",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ClusterIdentifier": "$cluster" },
     "metricName": "WLMQueueLength",
     "namespace": "AWS/Redshift",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "WLM Running Queries",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ClusterIdentifier": "$cluster" },
     "metricName": "WLMRunningQueries",
     "namespace": "AWS/Redshift",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Queries/Second",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "qps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dimensions": { "ClusterIdentifier": "$cluster" },
     "metricName": "QueriesCompletedPerSecond",
     "namespace": "AWS/Redshift",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Concurrency Scaling Clusters",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ClusterIdentifier": "$cluster" },
     "metricName": "ConcurrencyScalingActiveClusters",
     "namespace": "AWS/Redshift",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Resource Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "ClusterIdentifier": "$cluster" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/Redshift",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Disk Space Used %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "ClusterIdentifier": "$cluster" },
     "metricName": "PercentageDiskSpaceUsed",
     "namespace": "AWS/Redshift",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Query Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "WLM Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "ClusterIdentifier": "$cluster" },
     "metricName": "WLMQueueLength",
     "namespace": "AWS/Redshift",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "WLM Running Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "ClusterIdentifier": "$cluster" },
     "metricName": "WLMRunningQueries",
     "namespace": "AWS/Redshift",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Queries Completed Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "qps" } },
   "targets": [
    {
     "dimensions": { "ClusterIdentifier": "$cluster" },
     "metricName": "QueriesCompletedPerSecond",
     "namespace": "AWS/Redshift",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Query Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "dimensions": { "ClusterIdentifier": "$cluster" },
     "metricName": "QueryDuration",
     "namespace": "AWS/Redshift",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  { "title": "I/O & Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Disk Throughput (Read / Write)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "dimensions": { "ClusterIdentifier": "$cluster" },
     "metricName": "ReadThroughput",
     "namespace": "AWS/Redshift",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "dimensions": { "ClusterIdentifier": "$cluster" },
     "metricName": "WriteThroughput",
     "namespace": "AWS/Redshift",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Network Throughput (Receive / Transmit)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "dimensions": { "ClusterIdentifier": "$cluster" },
     "metricName": "NetworkReceiveThroughput",
     "namespace": "AWS/Redshift",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "dimensions": { "ClusterIdentifier": "$cluster" },
     "metricName": "NetworkTransmitThroughput",
     "namespace": "AWS/Redshift",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Database Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "ClusterIdentifier": "$cluster" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/Redshift",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  }
 ]
}