{
 "title": "AWS Route53 Overview",
 "tags": [
  "aws",
  "cloudwatch",
  "route53",
  "dns"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "cloudwatch" },
   {
    "name": "region",
    "label": "Region",
    "query": "us-east-1,us-east-2,us-west-1,us-west-2,eu-west-1,eu-west-2,eu-west-3,eu-central-1,eu-north-1,ap-northeast-1,ap-northeast-2,ap-southeast-1,ap-southeast-2,ap-south-1,sa-east-1,ca-central-1"
   },
   {
    "name": "health_check",
    "label": "Health Check",
    "query": {}
   },
   {
    "name": "hosted_zone",
    "label": "Hosted Zone",
    "query": {}
   },
   {
    "name": "resolver_endpoint",
    "label": "Resolver Endpoint",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Health Check Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Health Check Status",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "HealthCheckId": "$health_check" },
     "metricName": "HealthCheckStatus",
     "namespace": "AWS/Route53",
     "period": "60",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Minimum"
    }
   ]
  },
  {
   "title": "Health Check % Healthy",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "HealthCheckId": "$health_check" },
     "metricName": "HealthCheckPercentageHealthy",
     "namespace": "AWS/Route53",
     "period": "60",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Connection Time",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "HealthCheckId": "$health_check" },
     "metricName": "ConnectionTime",
     "namespace": "AWS/Route53",
     "period": "60",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Time to First Byte",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "HealthCheckId": "$health_check" },
     "metricName": "TimeToFirstByte",
     "namespace": "AWS/Route53",
     "period": "60",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "SSL Handshake Time",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "HealthCheckId": "$health_check" },
     "metricName": "SSLHandshakeTime",
     "namespace": "AWS/Route53",
     "period": "60",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Child Health Checks Healthy",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "HealthCheckId": "$health_check" },
     "metricName": "ChildHealthCheckHealthyCount",
     "namespace": "AWS/Route53",
     "period": "60",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "DNS Queries",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "HostedZoneId": "$hosted_zone" },
     "metricName": "DNSQueries",
     "namespace": "AWS/Route53",
     "period": "60",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "Health Check Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Health Check Status Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "HealthCheckId": "$health_check" },
     "metricName": "HealthCheckStatus",
     "namespace": "AWS/Route53",
     "period": "60",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Minimum"
    }
   ]
  },
  {
   "title": "Health Check % Healthy Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "HealthCheckId": "$health_check" },
     "metricName": "HealthCheckPercentageHealthy",
     "namespace": "AWS/Route53",
     "period": "60",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Child Health Checks Healthy Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "HealthCheckId": "$health_check" },
     "metricName": "ChildHealthCheckHealthyCount",
     "namespace": "AWS/Route53",
     "period": "60",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Health Check Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Connection Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "HealthCheckId": "$health_check" },
     "metricName": "ConnectionTime",
     "namespace": "AWS/Route53",
     "period": "60",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "SSL Handshake Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "HealthCheckId": "$health_check" },
     "metricName": "SSLHandshakeTime",
     "namespace": "AWS/Route53",
     "period": "60",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Time to First Byte",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "HealthCheckId": "$health_check" },
     "metricName": "TimeToFirstByte",
     "namespace": "AWS/Route53",
     "period": "60",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  },
  { "title": "DNS Query Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "DNS Queries Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "HostedZoneId": "$hosted_zone" },
     "metricName": "DNSQueries",
     "namespace": "AWS/Route53",
     "period": "60",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "Route53 Resolver Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Resolver Query Volume (Inbound / Outbound)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "EndpointId": "$resolver_endpoint" },
     "metricName": "InboundQueryVolume",
     "namespace": "AWS/Route53Resolver",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "EndpointId": "$resolver_endpoint" },
     "metricName": "OutboundQueryVolume",
     "namespace": "AWS/Route53Resolver",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  }
 ]
}